name: Rename Files with Colons

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Replace with the branch you want to monitor

jobs:
  rename-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find and rename files with colons
        run: |
          # Find all files with colons in their names
          for file in $(git ls-tree -r --name-only HEAD | grep ':'); do
            # Replace colons with dashes
            new_file=$(echo "$file" | sed 's/:/-/g')
            echo "Renaming $file to $new_file"
            git mv "$file" "$new_file"
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b renamed-files # Create a new branch for renamed files
          git commit -am "Renamed files to remove colons for compatibility"
          git push origin renamed-files
